

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_SPECIFIC_CATEGORY = 'SET_SPECIFIC_CATEGORY';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const GET_NEEDED_PRODUCT = 'GET_NEEDED_PRODUCT';
export const ADD_PRODUCT_TO_FAVS = 'ADD_PRODUCT_TO_FAVS';